# Generated by Django 4.1.5 on 2023-01-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
