# Generated by Django 4.1.5 on 2023-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_sock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='socks',
            field=models.ManyToManyField(to='main_app.sock'),
        ),
    ]
